/** Declaration file generated by dts-gen */

export = gulp_minify_inline;

declare function gulp_minify_inline(opt: any): any;

declare namespace gulp_minify_inline {
    const prototype: {
    };

}

