/** Declaration file generated by dts-gen */

export = glob_watcher;

declare function glob_watcher(glob: any, options: any, cb: any): any;

declare namespace glob_watcher {
    const prototype: {
    };

}

